apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: adwera/go-ts-auth-service
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: adwera/go-ts-data-service
      context: data
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: './**/*.go'
    - image: adwera/gots-listener-service
      context: listener
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: './**/*.go'
