apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: go-ts-auth-service
          image: adwera/go-ts-auth-service
          env:
            - name: MONGO_URI
              value: 'mongodb://admin:password@auth-mongo-service:27017/auth?authSource=admin'
            - name: REDIS_HOST
              value: 'auth-redis-service'
            - name: AMQP_CONNECTION_STRING
              value: amqp://guest:guest@rabbitmq
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-key
                  key: COOKIE_KEY
            - name: GOTS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: gots-client-id
                  key: GOTS_CLIENT_ID
            - name: GOTS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gots-client-secret
                  key: GOTS_CLIENT_SECRET 
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: web-port
      protocol: TCP
      port: 5000
      targetPort: 5000