apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - name: go-ts-data-service
          image: adwera/go-ts-data-service
          env:
            - name: DATA_MONGO_URI
              value: 'mongodb://data-mongo-service:27017/data'
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  selector:
    app: data
  ports:
    - name: web-port
      protocol: TCP
      port: 5001
      targetPort: 5001