apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-ts-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: app-k8s.io
      http:
        paths:
          - path: /auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 5000
          - path: /data/?(.*)
            pathType: Prefix
            backend:
              service:
                name: data-service
                port:
                  number: 5001